# Generated by Django 2.2.4 on 2019-10-23 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0002_auto_20191023_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='photo',
            field=models.ImageField(max_length=200, upload_to='photos/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(max_length=200, upload_to='photos/', verbose_name='Image'),
        ),
    ]
